// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTT.Data.NTTDBContext.NTTContexts;

namespace NTT.Data.NTTDBContext.Migrations.ScrapingSystemDbMigrations
{
    [DbContext(typeof(ScrapingSystemDbContext))]
    partial class ScrapingSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NTT.Data.EntityModel.ScrapingSytemEntity.ScrapingConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Business")
                        .HasColumnType("bigint");

                    b.Property<string>("ConfigData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreateById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueueKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdateById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ScrapingConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
